In [1]:
import tensorflow as tf

# Check if GPU is available
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

# Print GPU details
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    for gpu in gpus:
        print(gpu)
else:
    print("No GPU found.")


Num GPUs Available:  1
PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


In [2]:
!pip install pandas
import pandas as pd


In [3]:
df=pd.read_csv("happiness_quotes.csv")

In [4]:
#iski excel file m jake quotes copy kri aur "" hatadi vscode se aur txt file m save 

In [5]:
file_path = r'C:\Users\asus\Desktop\LSTM\Quotetxt.txt'
with open(file_path, 'r', encoding='latin-1') as file:
    faqs = file.read()


In [10]:
faqs


'The Paradoxical Commandments\nFor every minute you are angry you lose sixty seconds of happiness.\nLove is that condition in which the happiness of another person is essential to your own.\nFolks are usually about as happy as they make their minds up to be.\nTime you enjoy wasting is not wasted time.\nIt\'s so hard to forget pain, but it\'s even harder to remember sweetness. We have no scar to show for happiness. We learn so little from peace.\nHappiness in intelligent people is the rarest thing I know.\nThe Seven Social Sins are:\nYou will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.\nHappiness is when what you think, what you say, and what you do are in harmony.\nThere\'s nothing like deep breaths after laughing that hard. Nothing in the world like a sore stomach for the right reasons.\nEvery man has his secret sorrows which the world knows not; and often times we call a man cold when he is o

In [10]:
len(faqs.split("\n"))

2991

In [17]:
count=0
for sentence in faqs.split("\n"):
    if(len(sentence)<150):
        count=count+1;

In [18]:
count

1988

In [19]:
str=""

In [21]:
for sentence in faqs.split("\n"):
    if(len(sentence)<150):
        str=str+ sentence + "\n"

In [23]:
for sentence in str.split("\n"):
  print(sentence)

The Paradoxical Commandments
For every minute you are angry you lose sixty seconds of happiness.
Love is that condition in which the happiness of another person is essential to your own.
Folks are usually about as happy as they make their minds up to be.
Time you enjoy wasting is not wasted time.
It's so hard to forget pain, but it's even harder to remember sweetness. We have no scar to show for happiness. We learn so little from peace.
Happiness in intelligent people is the rarest thing I know.
The Seven Social Sins are:
You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.
Happiness is when what you think, what you say, and what you do are in harmony.
There's nothing like deep breaths after laughing that hard. Nothing in the world like a sore stomach for the right reasons.
Every man has his secret sorrows which the world knows not; and often times we call a man cold when he is only sad.
Happin

In [25]:
len(str.split("\n"))

1989

In [32]:
faqs=str

In [33]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [34]:
tokenizer = Tokenizer()

In [35]:
tokenizer.fit_on_texts([faqs])

In [36]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'of': 3,
 'is': 4,
 'you': 5,
 'and': 6,
 'a': 7,
 'happiness': 8,
 'in': 9,
 'we': 10,
 'be': 11,
 'it': 12,
 'that': 13,
 'are': 14,
 'your': 15,
 'happy': 16,
 'i': 17,
 'not': 18,
 'for': 19,
 'with': 20,
 'our': 21,
 'life': 22,
 'what': 23,
 'if': 24,
 'will': 25,
 'can': 26,
 'when': 27,
 'as': 28,
 'have': 29,
 'but': 30,
 'on': 31,
 'do': 32,
 'or': 33,
 'one': 34,
 'all': 35,
 'there': 36,
 'no': 37,
 'who': 38,
 'people': 39,
 'love': 40,
 'make': 41,
 'us': 42,
 'more': 43,
 'time': 44,
 'only': 45,
 'my': 46,
 'was': 47,
 'so': 48,
 'never': 49,
 'an': 50,
 'about': 51,
 'must': 52,
 'yourself': 53,
 'than': 54,
 'from': 55,
 'how': 56,
 'world': 57,
 'at': 58,
 'me': 59,
 'by': 60,
 'things': 61,
 'own': 62,
 'like': 63,
 'being': 64,
 'want': 65,
 'they': 66,
 'always': 67,
 "it's": 68,
 'this': 69,
 'day': 70,
 'know': 71,
 'just': 72,
 'way': 73,
 'out': 74,
 'he': 75,
 "don't": 76,
 'find': 77,
 'something': 78,
 'joy': 79,
 'thing': 80,
 'good':

In [37]:
len(tokenizer.word_index)

4330

In [38]:
for sentence in faqs.split("\n"):
    print(sentence)
    break

The Paradoxical Commandments


In [39]:
#first sentence

In [40]:
#ab aise sentences ko numbers m convert karo

In [41]:
for sentence in faqs.split("\n"):
    print(tokenizer.texts_to_sequences([sentence]))#double list aagya toh aage 0  lagago

[[1, 1205, 1893]]
[[19, 123, 1894, 5, 14, 733, 5, 375, 914, 1206, 3, 8]]
[[40, 4, 13, 1895, 9, 88, 1, 8, 3, 269, 111, 4, 1207, 2, 15, 62]]
[[1896, 14, 734, 51, 28, 16, 28, 66, 41, 141, 614, 90, 2, 11]]
[[44, 5, 258, 915, 4, 18, 1897, 44]]
[[68, 48, 200, 2, 182, 167, 30, 68, 124, 916, 2, 270, 917, 10, 29, 37, 1898, 2, 376, 19, 8, 10, 130, 48, 168, 55, 146]]
[[8, 9, 1899, 39, 4, 1, 1900, 80, 17, 71]]
[[1, 1901, 471, 1902, 14]]
[[5, 25, 49, 11, 16, 24, 5, 420, 2, 421, 19, 23, 8, 615, 3, 5, 25, 49, 91, 24, 5, 14, 342, 19, 1, 472, 3, 22]]
[[8, 4, 27, 23, 5, 89, 23, 5, 201, 6, 23, 5, 32, 14, 9, 473]]
[[616, 93, 63, 422, 1903, 231, 918, 13, 200, 93, 9, 1, 57, 63, 7, 1904, 1905, 19, 1, 97, 617]]
[[123, 100, 108, 213, 150, 919, 88, 1, 57, 920, 18, 6, 143, 164, 10, 474, 7, 100, 1208, 27, 75, 4, 45, 214]]
[[8, 4, 18, 78, 618, 241, 12, 178, 55, 15, 62, 297]]
[[475, 15, 476, 60, 282, 18, 377, 475, 15, 22, 60, 423, 18, 378]]
[[735, 53]]
[[24, 43, 3, 42, 1906, 424, 6, 736, 6, 535, 1209, 1907, 1210, 1

In [42]:
for sentence in faqs.split("\n"):
    print(tokenizer.texts_to_sequences([sentence])[0])

[1, 1205, 1893]
[19, 123, 1894, 5, 14, 733, 5, 375, 914, 1206, 3, 8]
[40, 4, 13, 1895, 9, 88, 1, 8, 3, 269, 111, 4, 1207, 2, 15, 62]
[1896, 14, 734, 51, 28, 16, 28, 66, 41, 141, 614, 90, 2, 11]
[44, 5, 258, 915, 4, 18, 1897, 44]
[68, 48, 200, 2, 182, 167, 30, 68, 124, 916, 2, 270, 917, 10, 29, 37, 1898, 2, 376, 19, 8, 10, 130, 48, 168, 55, 146]
[8, 9, 1899, 39, 4, 1, 1900, 80, 17, 71]
[1, 1901, 471, 1902, 14]
[5, 25, 49, 11, 16, 24, 5, 420, 2, 421, 19, 23, 8, 615, 3, 5, 25, 49, 91, 24, 5, 14, 342, 19, 1, 472, 3, 22]
[8, 4, 27, 23, 5, 89, 23, 5, 201, 6, 23, 5, 32, 14, 9, 473]
[616, 93, 63, 422, 1903, 231, 918, 13, 200, 93, 9, 1, 57, 63, 7, 1904, 1905, 19, 1, 97, 617]
[123, 100, 108, 213, 150, 919, 88, 1, 57, 920, 18, 6, 143, 164, 10, 474, 7, 100, 1208, 27, 75, 4, 45, 214]
[8, 4, 18, 78, 618, 241, 12, 178, 55, 15, 62, 297]
[475, 15, 476, 60, 282, 18, 377, 475, 15, 22, 60, 423, 18, 378]
[735, 53]
[24, 43, 3, 42, 1906, 424, 6, 736, 6, 535, 1209, 1907, 1210, 12, 104, 11, 7, 1908, 57]
[66, 2

In [13]:
#ab pair bnanae h eg first sentence h 153 1696 3 toh agar 153 input ho toh 1696 aajaye

In [43]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [44]:
input_sequences

[[1, 1205],
 [1, 1205, 1893],
 [19, 123],
 [19, 123, 1894],
 [19, 123, 1894, 5],
 [19, 123, 1894, 5, 14],
 [19, 123, 1894, 5, 14, 733],
 [19, 123, 1894, 5, 14, 733, 5],
 [19, 123, 1894, 5, 14, 733, 5, 375],
 [19, 123, 1894, 5, 14, 733, 5, 375, 914],
 [19, 123, 1894, 5, 14, 733, 5, 375, 914, 1206],
 [19, 123, 1894, 5, 14, 733, 5, 375, 914, 1206, 3],
 [19, 123, 1894, 5, 14, 733, 5, 375, 914, 1206, 3, 8],
 [40, 4],
 [40, 4, 13],
 [40, 4, 13, 1895],
 [40, 4, 13, 1895, 9],
 [40, 4, 13, 1895, 9, 88],
 [40, 4, 13, 1895, 9, 88, 1],
 [40, 4, 13, 1895, 9, 88, 1, 8],
 [40, 4, 13, 1895, 9, 88, 1, 8, 3],
 [40, 4, 13, 1895, 9, 88, 1, 8, 3, 269],
 [40, 4, 13, 1895, 9, 88, 1, 8, 3, 269, 111],
 [40, 4, 13, 1895, 9, 88, 1, 8, 3, 269, 111, 4],
 [40, 4, 13, 1895, 9, 88, 1, 8, 3, 269, 111, 4, 1207],
 [40, 4, 13, 1895, 9, 88, 1, 8, 3, 269, 111, 4, 1207, 2],
 [40, 4, 13, 1895, 9, 88, 1, 8, 3, 269, 111, 4, 1207, 2, 15],
 [40, 4, 13, 1895, 9, 88, 1, 8, 3, 269, 111, 4, 1207, 2, 15, 62],
 [1896, 14],
 [1896, 14,

In [45]:
#now sbki length same so 0 padding

In [46]:
max_len = max([len(x) for x in input_sequences])

In [47]:
max_len

31

In [48]:
# max length of code itni h

In [49]:
#ab 0 padding is length pe


In [50]:
#max_len=100 jb data km ni kya tha tb maxlen 700 aarhi thi process ni horhi thi

In [51]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [52]:
len(padded_input_sequences[0])

31

In [53]:
padded_input_sequences[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    1, 1205])

In [54]:
#ab dekh jaise 00345 h toh input 003 hai output 4 aur input 0034 h aur output 5

In [55]:
#aise x aur y extract

In [56]:
X = padded_input_sequences[:,:-1]#0034 agya
y = padded_input_sequences[:,-1]#5 isme

In [57]:
len(X)

28272

In [58]:
len(y)

28272

In [59]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=4331)#oHE kara h basically hr y ko ek value deddi 0100000 is type hr word ko
# th utne classifiers chahiye jitne words ho

In [60]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1])

In [61]:
y.shape

(28272, 4331)

In [63]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [62]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [68]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(input_dim=4331, output_dim=100, input_length=30))
model.add(LSTM(150, return_sequences=True))  # Set return_sequences=True if feeding into another LSTM
model.add(LSTM(150))  # By default, LSTM expects sequences from the previous layer
model.add(Dense(4331, activation='softmax'))

# Compile your model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Optionally, print model summary
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 30, 100)           433100    
                                                                 
 lstm_2 (LSTM)               (None, 30, 150)           150600    
                                                                 
 lstm_3 (LSTM)               (None, 150)               180600    
                                                                 
 dense_1 (Dense)             (None, 4331)              653981    
                                                                 
Total params: 1,418,281
Trainable params: 1,418,281
Non-trainable params: 0
_________________________________________________________________


In [69]:
len(X[0])

30

In [70]:
len(y[0])

4331

In [71]:
model.fit(X, y, epochs=100, batch_size=32)  


Epoch 1/100
884/884 [==============================] - 27s 20ms/step - loss: 6.5860 - accuracy: 0.0431
Epoch 2/100
884/884 [==============================] - 12s 14ms/step - loss: 6.1444 - accuracy: 0.0680
Epoch 3/100
884/884 [==============================] - 11s 12ms/step - loss: 5.8864 - accuracy: 0.0907
Epoch 4/100
884/884 [==============================] - 11s 13ms/step - loss: 5.6159 - accuracy: 0.1185
Epoch 5/100
884/884 [==============================] - 13s 14ms/step - loss: 5.3612 - accuracy: 0.1347
Epoch 6/100
884/884 [==============================] - 11s 13ms/step - loss: 5.1500 - accuracy: 0.1472
Epoch 7/100
884/884 [==============================] - 11s 12ms/step - loss: 4.9712 - accuracy: 0.1567
Epoch 8/100
884/884 [==============================] - 11s 12ms/step - loss: 4.8051 - accuracy: 0.1634
Epoch 9/100
884/884 [==============================] - 10s 12ms/step - loss: 4.6475 - accuracy: 0.1721
Epoch 10/100
884/884 [==============================] - 11s 12ms/step - l

In [79]:
import time
import numpy as np
text = "People"

for i in range(13):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=30, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      

1/1 [==============================] - 0s 26ms/step
People expected
1/1 [==============================] - 0s 23ms/step
People expected something
1/1 [==============================] - 0s 17ms/step
People expected something for
1/1 [==============================] - 0s 23ms/step
People expected something for nothing
1/1 [==============================] - 0s 22ms/step
People expected something for nothing that’s
1/1 [==============================] - 0s 22ms/step
People expected something for nothing that’s why
1/1 [==============================] - 0s 15ms/step
People expected something for nothing that’s why they
1/1 [==============================] - 0s 25ms/step
People expected something for nothing that’s why they did
1/1 [==============================] - 0s 24ms/step
People expected something for nothing that’s why they did nothing
1/1 [==============================] - 0s 22ms/step
People expected something for nothing that’s why they did nothing so
1/1 [============